### ISSUE TITLE
Scalatest is not working for spurious reason !

### ISSUE THREAD

**Issue by lsarrazin** [lsarrazin/kafka-consumer-alpakka#1]
```
sbt:kafka-alpakka-consumer-actor> test
[info] Run completed in 156 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[success] Total time: 2 s, completed 2 juil. 2018 22:33:22
```
or from Eclipse
```
*** RUN ABORTED ***
```

**Comment by GBLikan** [comment]
Problem was in the defining of the TestKit ActorSystem. Tests from the suite are correctly detected now (in branch 0.3), though I'm still working on writing some meaningful ones.

**Comment by GBLikan** [comment]
Finally got some actually meaningful tests working. The testkit handling of the ActorSystem is not very intuitive, and the documentation is severely lacking.
